database: state.db
log-level: debug

hosts:
  testhost:
    uri: localhost

checks:
  - name: http status
    cron: "*/10 * * * * ?"
    hosts:
      - testhost
    url: https://httpbin.org/status/200
    module: http-keepalive
    http-method: "head"
    expected-statuses:
      - 200
      - 201

  - name: special script
    hosts:
      - testhost
    cron: "*/10 * * * * ?"
    module: script
    file: /tmp/myscript

  - name: disk usage on /dev/sda1
    hosts:
      - testhost
    cron: "*/10 * * * * ?"
    module: disk-usage
    device: /dev/sda
    threshold: 80

  - name: mariadb service
    hosts:
      - testhost
    notify:
      - sys
    cron: "*/10 * * * * ?"
    module: systemd-service
    service: mariadb

notify:
  sys:
    description: we rock!
    emails:
      - me@example.com

mail:
  from: mee6@example.com
  mode: console  # local /smtp / console

http:
  port: 3001
