hosts:
  db:
    hostname: seequestor@web1.london1.sq:22
    key: ~/.ssh/id_rsa

  web1:
    hostname: mysshconfigname

checks:
  - name: Disk usage on /dev/sda1
    hosts:
      - db  # supports both hosts and groups
      - web1
    cron: "*/1 * * * *"  # cron expression, not in phase 1
    notify: sys
    module: disk-usage
    device: /dev/sda1
    threshold: 80

  - name: Check if nginx is up and running
    hosts:
      - web1
    cron: "@daily"
    notify: sys
    module: service
    service: nginx

notify:
  sys:
    description: The systems guys
    email:  # generic for both yellow and red
      - john.doe@example.com
      - jane.doe@example.com
