database: state.db
log-level: debug

hosts:
  targaryen:
    uri: targaryen

checks:
  - name: disk usage on /dev/md1
    hosts:
      - targaryen
    cron: "*/10 * * * * ?"
    notify: sys
    module: disk-usage
    device: /dev/md1
    threshold: 80

  - name: docker service
    hosts:
      - targaryen
    cron: "*/10 * * * * ?"
    notify: sys
    module: service
    service: docker

# - name: special script
#   hosts:
#     - targaryen
#   cron: "*/5 * * * * ?"
#   notify: sys
#   module: script
#   file: /tmp/myscript

# - name: check if nginx is up and running
#   hosts:
#     - baoqu
#   cron: "*/5 * * * * ?"
#   notify: test
#   module: service
#   service: nginx
#
# - name: say hi
#   hosts:
#     - entity
#   cron: "*/5 * * * * ?"
#   notify: test
#   module: script
#   file: /tmp/myscript
#   # args: noneeded

notify:
  sys:
    description: we rock!
    emails:
      - me@example.com

mail:
  from: mee6@example.com
  mode: console  # local /smtp / console

http:
  port: 3001
