database:
  path: state.db
  debounce: 3000

log-level: debug

hosts:
  testhost:
    uri: localhost

checks:
  - name: http status
    cron: "*/10 * * * * ?"
    hosts:
      - testhost
    url: https://httpbin.org/status/200
    module: http-keepalive
    http-method: "head"
    expected-statuses:
      - 200
      - 201

  - name: special script
    hosts:
      - testhost
    cron: "*/10 * * * * ?"
    module: user-script
    file: /tmp/myscript

  - name: disk usage on /dev/sda1
    hosts:
      - testhost
    cron: "*/10 * * * * ?"
    module: disk-usage
    device: /dev/sda1
    threshold: 80

  - name: mariadb service
    hosts:
      - testhost
    cron: "*/10 * * * * ?"
    module: systemd-service
    service: mariadb

notify:
  sys:
    type: "email"
    emails:
      - me@example.com

email:
  from: mee6@example.com
  mode: console  # local /smtp / console

http:
  port: 3001
