hosts:
  db:
    address: 192.168.1.1  # supports db.domain.com
    port: 22
    username: whoever
    key: ~/.ssh/id_rsa

checks:
  - name: Disk usage on /dev/sda1
    hosts:
      - db  # supports both hosts and groups
      - web1
      - web2
    cron: 5 * * * *  # cron expression, not in phase 1
    notify: sys
    module: disk-usage
    device: /dev/sda1
    threshold: 80

  - name: Check if nginx is up and running
    hosts:
      - web
    cron: @daily
    notify: sys
    module: service
    service: nginx

notify:
  sys:
    description: The systems guys
    email:  # generic for both yellow and red
      - john.doe@example.com
      - jane.doe@example.com
