# The database service configuration. If not provided, the persistence
# service will be disabled, and all information will only reside on memory.

database:
  path: state.db  # A path where the db will be saved
  debounce: 3000  # A timeframe for wait on state modifications before full disk persistence.

# The logging configuration.

log-level: info

# A directory list when to search additional modules (optional)

modules:
 - target/modules
 - /usr/share/mee6/modules

# A map of of posible hosts

hosts:
  testhost:
    uri: localhost

# A list of all checks

checks:
  - name: http status
    cron: "*/10 * * * * ?"
    hosts:
      - localhost
    url: https://httpbin.org/status/200
    tags:
      - foo
    module: http-keepalive
    http-method: "head"
    expected-statuses:
      - 200
      - 201

  - name: special script
    hosts:
      - testhost
    cron: "*/10 * * * * ?"
    tags:
      - bar
    module: user-script

  - name: disk usage on /dev/sda1
    hosts:
      - testhost
    cron: "*/10 * * * * ?"
    module: disk-usage
    device: /dev/sda1
    threshold: 80

  - name: mariadb service
    hosts:
      - testhost
    cron: "*/10 * * * * ?"
    module: systemd-service
    service: mariadb

# A map of notification groups (optional)

notify:
  sys:
    type: "email"
    emails:
      - me@example.com

# The email service configuration. If no configuration is provided,
# the email service will be disabled.

email:
  from: mee6@example.com
  mode: console  # local /smtp / console

# The http server service configuration. If no configuration is
# provided, the http service will be disabled.

http:
  port: 3001
  graphiql: true

  users:
    admin: B5QP3MKXJCifhSiVOK3S4w$1CWZ7pbxhGuUf6udk2F7p4ppFRYmYoIsCpDVkcguqS8
